#pragma config(Sensor, S3,     light,          sensorNone)
#pragma config(Sensor, S4,     sonar,          sensorNone)
#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void stopr()
{
	motor[r]=0;
	motor[l]=0;
	wait1Msec(1000);
}

void little()
{
	motor[r]=50;
	motor[l]=50;
	wait1Msec(900);
}

void right()
{
	motor[r]=0;
	motor[l]=50;
	wait1Msec(1400);
}

void rightrev()
{
	motor[r]=0;
	motor[l]=-50;
	wait1Msec(1350);
}

void left()
{
	motor[r]=50;
	motor[l]=0;
	wait1Msec(1400);
}

void leftrev()
{
	motor[r]=-50;
	motor[l]=0;
	wait1Msec(1350);
}

void clear()
{
	nMotorEncoder[l]=0;
	nMotorEncoder[r]=0;
}


task main()
{
	int count=0;
	for(int i=0; i<3 ;i++)
	{
		little();
	stopr();
	right();
	clear();
	while(SensorValue(light)>50)
	{
		motor[r]=50;
		motor[l]=50;
	}
	if(SensorValue(sonar)!=260)
	{
		count++;
		nxtDisplayCenteredTextLine(1,"%d",count);
	}
	while(nMotorEncoder[l]>0 && nMotorEncoder[r]>0)
	{
		motor[r]=-50;
		motor[l]=-50;
	}
	stopr();
	rightrev();
	stopr();
	left();
	clear();
	while(SensorValue(light)>50)
	{
		motor[r]=50;
		motor[l]=50;
	}
	if(SensorValue(sonar)!=260)
	{
		count++;
		nxtDisplayCenteredTextLine(1,"%d",count);
	}
	stopr();
	while(nMotorEncoder[l]>0 && nMotorEncoder[r]>0)
	{
		motor[r]=-50;
		motor[l]=-50;
	}
	stopr();
	leftrev();
	stopr();
	while(SensorValue(light)>50)
	{
		motor[r]=50;
		motor[l]=50;
	}
}
}
