#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     ultra,          sensorSONAR)
#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void attd(int count)
{
	while(SensorValue[light]>50)
	{
		motor[l]=50;
		motor[r]=50;
	}
	motor[l]=0;
	motor[r]=0;
	wait1Msec(1000);
	if(SensorValue(ultra)>100)
	{
		count=count+1;
		nxtDisplayCenteredTextLine(count,"Present : %d",count);
	}
	else
	{
		attd(count);
	}

}


task main()
{
	int count = 0;

		attd(count);

	motor[l]=0;
	motor[r]=50;
	wait1Msec(900);

		attd(count);

}
