#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		if(SensorValue[l]<50)
		{
			motor[l] =0 ;
			motor[r] =50 ;
		}
		else
		{
			motor[l] =50 ;
			motor[r] =0 ;
		}
	}

}
