#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void clear()
{
	nMotorEncoder[l]=0;
	nMotorEncoder[r]=0;
}

void sence()
{
	while(SensorValue[light]>50)
	{
		motor[l] = 50;
		motor[r] = 50;
	}
}

void stopr()
{
	motor[l] = 0;
	motor[r] = 0;
	wait1Msec(1000);
}

task main()
{
	int l1,l2;
	clear();
	sence();
	stopr();

	l1=nMotorEncoder[l];

	while(nMotorEncoder[l]>0)
	{
		motor[l]=-50;
		motor[r]=-50;
	}
	stopr();

	clear();
	while(nMotorEncoder[l]<l1+150)
	{
		motor[l]=50;
		motor[r]=50;
	}
	sence();
	stopr();

	l2=nMotorEncoder[l];

	while(nMotorEncoder[l]>0)
	{
		motor[l]=-50;
		motor[r]=-50;
	}
	stopr();

	clear();
	while(nMotorEncoder[l]<l2+150)
	{
		motor[l]=50;
		motor[r]=50;
	}
	sence();
	stopr();

	while(nMotorEncoder[l]>0)
	{
		motor[l]=-50;
		motor[r]=-50;
	}
	stopr();

}
