#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void left()
{
	motor[r]=50;
	motor[l]=0;
	wait1Msec(1400);
}
void right()
{
	motor[r]=0;
	motor[l]=50;
	wait1Msec(1400);
}

void straight()
{
	motor[r]=50;
	motor[l]=50;
}

void stopr()
{
	motor[r]=0;
	motor[l]=0;
	wait1Msec(1000);
}
void rev()
{
	motor[r]=-50;
	motor[l]=-50;
	wait1Msec(700);
}
void rotrev()
{
  motor[r]=-50;
	motor[l]=0;
	wait1Msec(1350);
	stopr();
	motor[r]=0;
	motor[l]=50;
	wait1Msec(1350);
}
task main()
{
	while(true)
	{
		while(SensorValue(sonar)>30)
		{
			straight();
		}
		rev();
		left();
		if(SensorValue(sonar)<25)
		{
			rev();
			stopr();
			rotrev();
		}
		if(SensorValue(sonar)<25)
		{
			break;
		}
	}
}
