#pragma config(Sensor, S4,     ultra,          sensorSONAR)
#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void clear()
{
	nMotorEncoder[l]=0;
	nMotorEncoder[r]=0;
}

void stopr()
{
	motor[l]=0;
	motor[r]=0;
	wait1Msec(1000);
}

task main()
{
	for(int i=0;i<16;i++)
	{
		while(SensorValue(ultra)>40)
		{
			motor[l] = 50;
			motor[r] = 50;
		}
		stopr();
		clear();
		while(nMotorEncoder[l]<455)
		{
			motor[l]=50;
			motor[r]=0;
		}
		//wait1Msec(1350);
		stopr();
	}
}
