#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void straight(int i)
{
	motor[l]=50;
	motor[r]=50;
	wait1Msec(i);
}

void left()
{
	motor[l]=50;
	motor[r]=0;
	wait1Msec(1360);
}

void stopr()
{
	motor[l]=0;
	motor[r]=0;
	wait1Msec(1000);
}

task main()
{
	for (int i=0;i<8;i++)
	{
		straight(4000);
		stopr();

		left();
		stopr();

		straight(4000);
		stopr();

		left();
		stopr();
	}

}
