#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void clear()
{
	nMotorEncoder[l]=0;
	nMotorEncoder[r]=0;
}

void stopr()
{
	motor[l]=0;
	motor[r]=0;
	wait1Msec(1000);
}
task main()
{
	for(int i=0;i<16;i++)
	{
		while(SensorValue[light]>50)
		{
			motor[l] = 50;
			motor[r] = 50;
		}
		motor[l]=40;
		motor[r]=40;
		wait1Msec(1000);
		//stopr();
		//motor[l]=50;
		//motor[r]=0;
		//wait1Msec(1150);
		stopr();
		clear();
		while(nMotorEncoder[l]<455)
		{
			motor[l]=50;
			motor[r]=0;
		}
		stopr();
	}

}
