#pragma config(Sensor, S3,     ultra,          sensorSONAR)
#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void clear()
{
	nMotorEncoder[l]=0;
	nMotorEncoder[r]=0;
}

void stopr()
{
	motor[l]=0;
	motor[r]=0;
	wait1Msec(700);
}

void sence()
{
	while(SensorValue(ultra)>70)
	{
		motor[l]=50;
		motor[r]=50;
	}
}

void right()
{
	clear();
	while(nMotorEncoder[l]<945)
	{
		motor[l]=50;
		motor[r]=0;
	}
	stopr();
}
void left()
{
	clear();
	while(nMotorEncoder[r]<970)
	{
		motor[l]=0;
		motor[r]=50;
	}
	stopr();
}

//--------------------------------------------------------------------------------------------
task main()
{
	while(true)
	{
		sence();
		right();
		sence();
		left();

	}
}
