#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void clear()
{
	nMotorEncoder[l]=0;
	nMotorEncoder[r]=0;
}

void stopr()
{
	motor[l]=0;
	motor[r]=0;
	wait1Msec(700);
}

void sence()
{
	while(SensorValue[light]>50)
	{
		motor[l]=50;
		motor[r]=50;
	}
}

void right()
{
	motor[l]=-50;
	motor[r]=-50;
	wait1Msec(400);
	stopr();
	clear();
	while(nMotorEncoder[l]<770)
	{
		motor[l]=50;
		motor[r]=0;
	}
	stopr();
}
void left()
{
	motor[l]=-50;
	motor[r]=-50;
	wait1Msec(400);
	stopr();
	clear();
	while(nMotorEncoder[r]<970)
	{
		motor[l]=0;
		motor[r]=50;
	}
	stopr();
}

//--------------------------------------------------------------------------------------------
task main()
{
	while(true)
	{
		sence();
		left();

		sence();
		right();

	}
}
