#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	nSyncedMotors = synchCB;
	nSyncedTurnRatio = 45;

	while(true)
	{
		motor[l] = 50;
		wait1Msec(7000);
	}
}
