#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		if (SensorValue[light]>50)
		{
			motor[l] = random(100);
			motor[r] = random(100);
		}
		else
		{
			motor[l]=-50;
			motor[r]=-50;
			wait1Msec(400);
			motor[l]=0;
			motor[r]=50;
			wait1Msec(random(1500));
		}

	}
}
